{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7961cfef-1167-4d43-8cc7-28c92b200db9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import camb\n",
    "\n",
    "# Configuração da página\n",
    "st.set_page_config(page_title=\"Redshift vs Idade do Universo\", layout=\"wide\")\n",
    "st.title(\"Evolução Temporal: Redshift x Idade do Universo ⏳\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "Esta ferramenta utiliza o motor do **CAMB** para calcular como a idade do universo (em bilhões de anos - Gyr) evolui à medida que avançamos no redshift ($z$).\n",
    "\"\"\")\n",
    "\n",
    "# Painel de controle no menu lateral\n",
    "with st.sidebar.form(\"form_idade_cosmologica\"):\n",
    "    st.header(\"Parâmetros Cosmológicos\")\n",
    "    H0 = st.slider(\"H0 (Constante de Hubble):\", 50.0, 85.0, 67.4, 0.5)\n",
    "    omch2 = st.slider(\"Ωc h² (Matéria Escura):\", 0.050, 0.250, 0.120, 0.005)\n",
    "    ombh2 = st.slider(\"Ωb h² (Bárions):\", 0.010, 0.040, 0.0224, 0.001)\n",
    "    \n",
    "    calcular_botao = st.form_submit_button(\"Gerar Gráfico de Evolução\")\n",
    "\n",
    "# Função para calcular a história de expansão com cache\n",
    "@st.cache_data\n",
    "def calcular_historia(H0_val, omch2_val, ombh2_val):\n",
    "    pars = camb.CAMBparams()\n",
    "    pars.set_cosmology(H0=H0_val, ombh2=ombh2_val, omch2=omch2_val, omk=0.0, tau=0.0544)\n",
    "    pars.InitPower.set_params(As=2.1e-9, ns=0.965)\n",
    "    \n",
    "    # Obtém a história de antecedentes (background)\n",
    "    results = camb.get_background(pars)\n",
    "    \n",
    "    # Gera um vetor de redshifts de 0 até 1000\n",
    "    z_array = np.linspace(0, 20, 500)\n",
    "    \n",
    "    # Extrai a idade em cada redshift (retorna em anos, convertemos para Bilhões de Anos - Gyr)\n",
    "    idades_gyr = np.array([results.age_at_z(z) for z in z_array])\n",
    "    \n",
    "    return z_array, idades_gyr\n",
    "\n",
    "# Executa o cálculo com os valores escolhidos\n",
    "z_vals, idade_vals = calcular_historia(H0, omch2, ombh2)\n",
    "\n",
    "# Plota o gráfico\n",
    "fig, ax = plt.subplots(figsize=(10, 5))\n",
    "plt.style.use('dark_background')\n",
    "\n",
    "ax.plot(z_vals, idade_vals, color='#38bdf8', linewidth=2.5, label='Modelo Atual')\n",
    "\n",
    "ax.set_xlabel('Redshift ($z$)', fontsize=12)\n",
    "ax.set_ylabel('Idade do Universo (Gyr)', fontsize=12)\n",
    "ax.set_title('Relação Idade do Universo x Redshift', fontsize=14)\n",
    "\n",
    "ax.grid(color='#334155', linestyle='-', linewidth=0.5, alpha=0.5)\n",
    "ax.legend(loc='upper right')\n",
    "\n",
    "st.pyplot(fig)\n",
    "\n",
    "# Informação complementar na tela\n",
    "st.info(f\"💡 **Idade atual estimada do Universo ($z=0$):** {idade_vals[0]:.2f} bilhões de anos.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
